<?php
function bakery_user_menu() {
    $items['welcome'] = array(
        'title' => 'Hi There!',
        'page callback' => 'welcome_new_user',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

//added the callback function which was missing
function welcome_new_user() {
    return "<p>Great Success!</p>";
}

//changed from bakery_user_login to bakery_user_user_login
//module name and hook name were overlapping
function bakery_user_user_login() {
    $_GET['destination'] = 'welcome';
}
